version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: cb-api-postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: class-booking-user
      POSTGRES_PASSWORD: class-booking-password
      POSTGRES_DB: class-booking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U class-booking-user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: cb-api-redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
